/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GameMachine {
    }
    interface GameToken {
        "source": string;
    }
}
declare global {
    interface HTMLGameMachineElement extends Components.GameMachine, HTMLStencilElement {
    }
    var HTMLGameMachineElement: {
        prototype: HTMLGameMachineElement;
        new (): HTMLGameMachineElement;
    };
    interface HTMLGameTokenElement extends Components.GameToken, HTMLStencilElement {
    }
    var HTMLGameTokenElement: {
        prototype: HTMLGameTokenElement;
        new (): HTMLGameTokenElement;
    };
    interface HTMLElementTagNameMap {
        "game-machine": HTMLGameMachineElement;
        "game-token": HTMLGameTokenElement;
    }
}
declare namespace LocalJSX {
    interface GameMachine {
    }
    interface GameToken {
        "source"?: string;
    }
    interface IntrinsicElements {
        "game-machine": GameMachine;
        "game-token": GameToken;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "game-machine": LocalJSX.GameMachine & JSXBase.HTMLAttributes<HTMLGameMachineElement>;
            "game-token": LocalJSX.GameToken & JSXBase.HTMLAttributes<HTMLGameTokenElement>;
        }
    }
}
